title: Project

# Sorting number scheme that is applied when page status is changed to `listed`
# More about page sorting: https://getkirby.com/docs/reference/panel/blueprints/page#sorting
num: date

icon: 📖

status:
  draft:
    label: Draft
    text: The note is still in draft mode. It can only be seen by editors with panel access.
  unlisted:
    label: In Review
    text: The note is online and can be visited with the direct URL. The team must still give the final go to publish it.
  listed:
    label: Published
    text: The note is online and listed in the blog

columns:
  - width: 2/3
    fields:
      info:
        label: Note pour l'italique dans le titre
        type: info
        text: Ajouter le caractère "*" autour d'un mot ou groupe de mots que vous souhaitez mettre en italique.
      text:
        type: blocks
        label: Résumé du projet
        fieldsets:
          - text
          - image
          - gallery
          - video

  - width: 1/3
    sections:
      meta:
        type: fields
        fields:
          cover: fields/cover
          dateStart:
            required: true
            label: Date de commencement
            type: date
            default: now
            display: YYYY-MM
          dateEnd:
            label: Date de fin
            type: date
            default: now
            display: YYYY-MM
          showMonth:
            type: toggle
            label: Afficher le mois
            default: true
            text:
              - non
              - oui
          author:
            label: Responsable
            type: multiselect
            options:
              type: query
              query: site.children.template("community").children.template("researcher")
          partners:
            label: Partenaires
            type: list
          team:
            label: Équipe
            type: list
          financement:
            label: Financement
            type: writer
            inline: true
            marks:
              - link
              - italic
          axes:
            label: Axe de recherche
            type: multiselect
            min: 1
            max: 1
            options:
              type: query
              query:  site.find('themes-et-axe-de-recherche').children.template('list-axes')
              text: "{{ item.title }}"
          themes:
            label: Thèmes
            type: multiselect
            min: 1
            options:
              type: query
              query: site.find('themes-et-axe-de-recherche').childrenAndDrafts.template('list-theme')
              text: "{{ item.title }}"
  - width: 2/3
    sections:
      all:
        extends: sections/project-file_chapter
