title: Project

# Sorting number scheme that is applied when page status is changed to `listed`
# More about page sorting: https://getkirby.com/docs/reference/panel/blueprints/page#sorting
num: date

icon: 📖

status:
  draft:
    label: Brouillon
    text: L'article est toujours en mode brouillon. Elle ne peut être vue que par les éditeurs ayant accès au panneau.
  unlisted:
    label: En attente de publication
    text: L'article n'est pas encore publiée. L'équipe doit toujours donner le feu vert final pour la publier.
  listed:
    label: Publié
    text: L'article est répertoriée dans l'archive et en ligne.

columns:
  - width: 2/3
    fields:
      info:
        label: Note pour l'italique dans le titre
        type: info
        text: Ajouter le caractère "*" autour d'un mot ou groupe de mots que vous souhaitez mettre en italique.
      text:
        type: blocks
        label: Résumé du projet
        fieldsets:
          - text
          - image
          - gallery
          - video

  - width: 1/3
    sections:
      meta:
        type: fields
        fields:
          cover:
            required: true
            extends: fields/cover
          dateStart:
            required: true
            label: Date de commencement
            type: date
            default: now
            display: YYYY-MM
          dateEnd:
            label: Date de fin
            type: date
            default: now
            display: YYYY-MM
          showMonth:
            type: toggle
            label: Afficher le mois
            default: true
            text:
              - non
              - oui
          author:
            required: true
            label: Responsable
            type: multiselect
            options:
              type: query
              query: site.children.template("community").children.template("researcher")
          partners:
            label: Partenaires
            type: list
            marks:
              - bold
              - italic
          team:
            label: Équipe
            type: list
            marks:
              - link
              - italic
          financement:
            required: true
            label: Financement
            type: writer
            inline: true
            marks:
              - link
              - italic
          Publications:
            label: Publications
            type: list
            marks:
              - link
              - italic
          axes:
            required: true
            label: Axe de recherche
            type: multiselect
            min: 1
            max: 1
            options:
              type: query
              query:  site.find('themes-et-axe-de-recherche').children.template('list-axes')
              text: "{{ item.title }}"
          themes:
            required: true
            label: Thèmes
            type: multiselect
            min: 1
            options:
              type: query
              query: site.find('themes-et-axe-de-recherche').childrenAndDrafts.template('list-theme')
              text: "{{ item.title }}"
  - width: 2/3
    sections:
      all:
        extends: sections/project-file_chapter
  - width: 2/3
    fields:
      connected:
        required: false
        label: Projet(s) connecté(s)
        type: multiselect
        options:
          type: query
          query: site.find("projects").children
          text: "{{ page.title }}"
          value: "{{ page.uuid }}"
  #        .children.template("researcher")
