title: Project

# Sorting number scheme that is applied when page status is changed to `listed`
# More about page sorting: https://getkirby.com/docs/reference/panel/blueprints/page#sorting
num: date

icon: 📖

status:
  draft:
    label: Draft
    text: The note is still in draft mode. It can only be seen by editors with panel access.
  unlisted:
    label: In Review
    text: The note is online and can be visited with the direct URL. The team must still give the final go to publish it.
  listed:
    label: Published
    text: The note is online and listed in the blog

columns:
  - width: 2/3
    fields:
      text:
        type: blocks
        label: Résumé du projet
        fieldsets:
          - text
          - image
          - gallery
          - video

  - width: 1/3
    sections:
      meta:
        type: fields
        fields:
          cover: fields/cover
          dateStart:
            required: true
            label: date de commencement
            type: date
            default: now
            display: YYYY-MM
          dateEnd:
            label: date de fin
            type: date
            default: now
            display: YYYY-MM
          author:
            label: Responsable
            type: multiselect
            options:
              type: query
              query: site.children.template("community").children.template("researcher")
          partners:
            label: Partenaires
            type: list
          team:
            label: Équipe
            type: multiselect
            options:
              type: query
              query: site.children.template("community").children.template("researcher")
          financement:
            label: Financement
            type:
          axe:
            label: Axe de recherche
            type: multiselect
            min: 1
            max: 1
            options:
              Métiers de la musique
              Musique et technologie
              Musique et société
              Interprétation historique
              Transmission
              Musique du monde
          theme:
            label: Thèmes
            type: multiselect
            min: 1
            options:
              Musique et mouvement
              Percussion
              Vents
              Diminution et ornementation
              Solmisation
              Informatique musicale (cf. Luis Naon)
              Pratique historiquement informée
              Claviers
              Chant
              Interprétation et ornementation
              Orchestre
              Recherche pédagogique
              Échanges culturels (cf. Xavier Bouvier)
              Analyse et théorie de la musique
              Geste et mouvement
              Musiques d’aujourd’hui
              Musique et arts performatifs
              Musique à Genève et en Suisse
              Métiers
              Santé du musicien-ne

  - width: 1/4
    fields:
      imagesFiles:
        label: Archive d'images (.ZIP)
        type: files
        query: page.files.template('archive')
        uploads:
          template: archive
  - width: 1/4
    fields:
      videoFiles:
        label: Fichiers video
        type: files
        query: page.files.template('video')
        uploads:
          template: video
  - width: 1/4
    fields:
      autioFiles:
        label: Fichiers audio
        type: files
        query: page.files.template('audio')
        uploads:
          template: audio
  - width: 1/4
    fields:
      pdfFiles:
        label: PDF
        type: files
        query: page.files.template('pdf')
        uploads:
          template: pdf
