blueprint: page

name: field.blocks.image.name
icon: image
preview: image
fields:
  image:
    label: field.blocks.image.name
    type: files
    query: model.images
    multiple: false
    uploads:
      template: blocks/image
  small_layout:
    label: Petite taille d'image
    type: toggle
    text:
      - 'non (grande image)'
      - 'oui (petite image)'
  link:
    label: lien
    type: url
  caption:
    label: Légende
    type: writer
    inline: true
    marks:
      - link
      - bold
      - italic
      - underline
