blueprint: page

name: field.blocks.video.name
icon: video
preview: video
fields:
  url:
    label: field.blocks.video.url.label
    type: url
    placeholder: field.blocks.video.url.placeholder
  toggle_ratio_1_1:
    width: 1/2
    label: Ratio 1/1
    type: toggle
    default: false
    text:
      - "non, vidéo horizontal"
      - "oui, vidéo carrée"
  caption:
    label: Légende
    type: writer
    inline: true
    marks:
      - link
      - bold
      - italic
      - underline
