blueprint: page

name: gallerie vidéo
icon: video
preview: fields
wysiwyg: true
fields:
  video_list:
    type: structure
    label: list des videos YouTube
    fields:
      url:
        label: field.blocks.video.url.label
        type: url
        placeholder: field.blocks.video.url.placeholder
      info:
        type: info
        text: lien video YouTube
  caption:
    label: Légende
    type: writer
    inline: true
    marks:
      - link
      - bold
      - italic
      - underline
