options:
  changeTitle: true

columns:
  - width: 1/4
    sections:
      projects:
        label: Contenus pédagogiques
        type: pages
        status: listed
        image:
          query: page.images.findBy("name", "cover")
          cover: true
        templates: projects
        layout: cards
        size: medium
        text: " "
  - width: 1/4
    sections:
      about:
        label: À propos
        type: pages
        status: listed
        image:
          query: page.images.findBy("name", "cover")
          cover: true
        templates: about
        layout: cards
        size: medium
        text: " "
  - width: 1/4
    sections:
      community:
        label: Communauté
        type: pages
        status: listed
        image:
          query: page.images.findBy("name", "cover")
          cover: true
        templates: community
        layout: cards
        size: medium
        text: " "

  - width: 1/4
    sections:
      themeList:
        label: Thématiques
        type: pages
        status: listed
        image:
          query: page.images.findBy("name", "cover")
          cover: true
        templates: theme-and-axes-list
        layout: cards
        size: medium
        text: " "
